compressionLevel: mixed

enableGlobalCache: true

enableStrictSsl: false

enableTelemetry: false

yarnPath: .yarn/releases/yarn-4.10.3.cjs

nodeLinker: node-modules

npmAlwaysAuth: true

npmRegistryServer: "https://repository.ext.icrc.org/repository/main-npm/"
