resources:
  repositories:
    - repository: vars
      type: git
      name: Pearlii/pearlii-pipelines-vars
      ref: refs/heads/main
    - repository: templates
      type: git
      name: DevOps Portal/pipelines-templates
      ref: refs/heads/main

trigger:
  batch: true
  branches:
    include:
      - refs/heads/main
  paths:
    exclude:
      - '**/*.md'
      - azure-pipelines-release.yml

name: 3.1.0-$(date:yyyyMMdd)$(rev:-rr)

pool:
  name: Build-Docker-Latest

variables:
  - template: vars-quality.yml@vars
jobs:
  - template: build/javascript/npm-build-jobs.yml@templates
    parameters:
#      poolName: Build-Docker-Latest
      gitBranchToPublishOn: refs/heads/main
      nodeJsVersion: 21.x
      doUseCorepack: false
      junitResultFile: junit.xml
      doSonarQubeScan: true
      doCheckmarxScan: true
      sonarProjectKeyPrefix: ${{variables.SONAR_PROJECT_PLATFORM}}
      sonarConfigMode: manual
      sonarSources: packages/esm-recent-activities-app,packages/esm-mhpss-dashboard-app,packages/esm-icrc-todo-widget-app,packages/esm-icrc-prp-dashboard-app,packages/esm-icrc-menu-buttons-app,packages/esm-icrc-last-visits-app,packages/esm-icrc-hsu-journey-app,packages/esm-icrc-homepage-header-app,packages/esm-icrc-hcd-dashboard-app,packages/esm-icrc-generic-table-app,packages/esm-icrc-erp-widget-app,packages/esm-icrc-data-sources,packages/esm-icrc-mental-health-app,packages/esm-icrc-transversal-app
      doCache: true
      cacheKeyFile: yarn.lock
      buildCommandLines:
        - command: npm install --global yarn
        - command: yarn install --immutable
        - command: yarn run verify
        - command: yarn jest --coverage
        - command: yarn dlx turbo run build --concurrency=1
      deployCommandLines:
        - command: yarn lerna version "$(Build.BuildNumber)" --no-git-tag-version --no-push --yes
        - command: git update-index --skip-worktree -- .npmrc .yarnrc.yml
        - command: git config user.email "s_tfs_build_p@gva.icrc.priv" && git config user.name "TFS Build" && git commit -m "$(Build.BuildNumber)" .
        - command: yarn ci:prepublish
        - command: git update-index --no-skip-worktree -- .npmrc .yarnrc.yml
      sonarCustomProperties: |
          sonar.javascript.junit.reportPaths=./junit.xml
          sonar.javascript.lcov.reportPaths=./coverage/lcov.info